import type { Metadata } from "next";
import { Geist } from "next/font/google"
import "./globals.css";
import Header from "../components/Header/Header";
import Providers from "./providers";

const geist = Geist({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "vanillaui",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={geist.className}>
      <body>
        <main className="mainContainer">
          <Header />
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
