import type { Metadata } from "next";
import { Geist } from "next/font/google"
import "./globals.css";
import Header from "../shared/Header/Header";
import Providers from "./providers";
import Footer from "@/shared/Footer/Footer";

const geist = Geist({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "vanillaui",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={geist.className}>
      <body>   
        <Header />
        <main>
          <Providers>{children}</Providers>
        </main>
        <Footer />   
      </body>
    </html>
  );
}
